version: "3.3"

services:
  # ------------------------------------------------------------------------------------------------------------ #
  #                                                      API                                                     #
  # ------------------------------------------------------------------------------------------------------------ #
  # auth-service:
  #   container_name: auth-service
  #   build:
  #     context: ./auth-service/
  #     dockerfile: ./dev.Dockerfile
  #   # depends_on:
  #   #   -mongodb:
  #   #     condition: service_started
  #   # volumes:
  #   #   - ./auth-service/:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=dev
  #   env_file: ./.auth-service.env
  #   command: ["npm", "start"]

  # # ------------------------------------------------------------------------------------------------------------ #
  # #                                                   DATABASE                                                   #
  # # ------------------------------------------------------------------------------------------------------------ #
  mongodb:
    container_name: mongodb
    image: mongo:4.4.9
    volumes:
      - ./mongodb_data/data/:/data/db
      - ./mongodb_data/config/:/data/configdb
    ports:
      - 27017:27017
    command: mongod
    healthcheck:
      test: ["CMD", "docker-healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 10

  # # ------------------------------------------------------------------------------------------------------------ #
  # #                                                     REDIS                                                    #
  # # ------------------------------------------------------------------------------------------------------------ #
  # redis:
  #   container_name: redis
  #   image: "redis:alpine"
  #   ports:
  #     - 6379:6379
